CREATE TABLE "GCG_5807_DOC_STAGE" (
 "RECORD_ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_RECORD_ID" UNIQUE USING 0,
 "RECORD_TIMESTAMP" DATETIME DEFAULT NOW() NOT NULL,
 "PROCESSED" BIT DEFAULT '0' NOT NULL,
 "FAILED" BIT DEFAULT '0' NOT NULL,
 "PROCESSED_TIMESTAMP" DATETIME,
 "FEEDBACK" LONGVARCHAR,
 "EXTERNAL_ID" CHAR(30) NOT NULL,
 "LINK_TYPE" INTEGER NOT NULL,
 "GROUP_NAME" CHAR(50),
 "LINK_KEY" CHAR(125) NOT NULL,
 "FILE_PATH" LONGVARCHAR NOT NULL,
 "DESCRIPTION" CHAR(30),
 "LINK_ID" INTEGER );
