CREATE TABLE "GCG_5807_REVIEW" (
 "RECORD_ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_RECORD_ID" UNIQUE USING 0,
 "RECORD_TIMESTAMP" DATETIME,
 "EXTERNAL_ORDER" CHAR(20),
 "LAST_MODIFIED" DATETIME,
 "MODIFIED_BY" CHAR(8),
 "APPROVED" BIT NOT NULL,
 "APPROVED_TIMESTAMP" DATETIME,
 "APPROVED_BY" CHAR(8),
 "PROCESSED" BIT DEFAULT '0' NOT NULL );
