CREATE TABLE "GCG_5807_CHANGE_LOG" (
 "TYPE" CHAR(20),
 "IDENTIFIER_1" CHAR(20),
 "IDENTIFIER_2" CHAR(20),
 "PROPERTY" CHAR(50),
 "ORIGINAL_VALUE" LONGVARCHAR,
 "NEW_VALUE" LONGVARCHAR,
 "GS_USER" CHAR(8),
 "CHANGED_TIMESTAMP" DATETIME DEFAULT NOW(),
 "PROCESSED" BIT DEFAULT '0' NOT NULL,
 "PROCESSED_TIMESTAMP" DATETIME,
 "RECORD_ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_RECORD_ID" UNIQUE USING 0,
 "INITIAL_VALUE" BIT DEFAULT '0' NOT NULL );
